vich_uploader:
    db_driver: orm

    mappings:
        imgs:
            uri_prefix: '%app.path.imgs%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public%app.path.imgs%'
